import Foundation

enum KnownServerErrorCode: String, Sendable {
    case invalidRequest = "invalid_request"
    case internalError = "internal_error"
    case authMissing = "auth_missing"
    case authInvalid = "auth_invalid"
    case authInvalidPayload = "auth_invalid_payload"
    case invalidInviteCode = "invalid_invite_code"
    case usernameTooShort = "username_too_short"
    case invalidEmail = "invalid_email"
    case emailAlreadyInUse = "email_already_in_use"
    case usernameAlreadyTaken = "username_already_taken"
    case accountAlreadyExists = "account_already_exists"
    case invalidCredentials = "invalid_credentials"
    case userNotFound = "user_not_found"
    case noFieldsToUpdate = "no_fields_to_update"
    case friendRequestSelf = "friend_request_self"
    case recipientNotFound = "recipient_not_found"
    case friendRequestAlreadyExists = "friend_request_already_exists"
    case friendRequestNotFound = "friend_request_not_found"
    case messageBodyRequired = "message_body_required"
    case messageMediaRequired = "message_media_required"
    case messageMediaInvalid = "message_media_invalid"
    case messageDimensionsInvalid = "message_dimensions_invalid"
    case notFriends = "not_friends"
    case invalidConversationId = "invalid_conversation_id"
    case paginationCursorConflict = "pagination_cursor_conflict"
    case conversationNotFound = "conversation_not_found"
    case invalidLastReadMessageId = "invalid_last_read_message_id"
    case fileRequired = "file_required"
    case invalidImageFile = "invalid_image_file"
}
